name: rl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.32.1
  - libzlib=1.2.11
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mypy=0.931
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - numexpr=2.7.3
  - numpy=1.22.3
  - openssl=3.0.0
  - pandas=1.4.1
  - pip=22.0.4
  - psutil=5.8.0
  - python=3.10.2
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2021.3
  - readline=8.1
  - setuptools=60.9.3
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - pip:
    - pyyaml==6.0
